// Copyright (c) 2025 Merge Layers Inc.
//
// This source code is licensed under the Business Source License 1.1
// (the "License"); you may not use this file except in compliance with the
// License. You may obtain a copy of the License at
//
//     https://github.com/malda-protocol/malda-zk-coprocessor/blob/main/LICENSE-BSL
//
// See the License for the specific language governing permissions and
// limitations under the License.

//! Generic types for Risc0 proving infrastructure.
//!
//! This module provides backend-agnostic types for ZK proof generation,
//! including session statistics, proof results, and configuration parameters.

use alloy::primitives::utils::parse_units;
use risc0_zkvm::Receipt;
use std::time::Duration;

/// Timeout duration for transaction confirmation.
///
/// The maximum time to wait for a transaction to be confirmed on the blockchain.
/// This is used for operations that require transaction confirmation, such as
/// submitting proof requests to the Boundless market.
pub const TX_TIMEOUT: Duration = Duration::from_secs(30);

/// Statistics for a ZK proof session.
///
/// Contains detailed information about the computational resources used during proof generation.
/// Useful for auditing, performance analysis, and understanding the cost of ZK proof generation.
#[derive(Debug, Clone)]
pub struct SessionStats {
    /// Number of proof segments generated by the ZKVM session.
    pub segments: usize,
    /// Total computational cycles used (all segments).
    pub total_cycles: u64,
    /// User-specific computational cycles (cycles spent on user logic).
    pub user_cycles: u64,
    /// Cycles used for memory paging operations.
    pub paging_cycles: u64,
    /// Reserved cycles for system operations.
    pub reserved_cycles: u64,
}

/// Information about a completed ZK proof via Bonsai.
///
/// Contains the proof receipt, session statistics, and timing information for a Bonsai proof session.
#[derive(Debug)]
pub struct BonsaiProveInfo {
    /// The ZK proof receipt containing the proof data (can be submitted on-chain).
    pub receipt: Receipt,
    /// Statistics about the proof generation session.
    pub stats: SessionStats,
    /// Unique identifier for the proof session (from Bonsai SDK).
    pub uuid: String,
    /// Time taken for STARK proof generation in seconds.
    pub stark_time: u64,
    /// Time taken for SNARK proof generation in seconds.
    pub snark_time: u64,
}

/// Parameters for configuring the Boundless market client and request offers.
///
/// Contains all configurable parameters for the Boundless market integration,
/// including pricing, timeouts, and auction settings.
#[derive(Debug, Clone)]
pub struct BoundlessParams {
    /// Maximum price per cycle for automatic pricing calculations (in gwei).
    pub max_price_per_cycle: u64,
    /// Minimum price per cycle for automatic pricing calculations (in gwei).
    pub min_price_per_cycle: u64,
    /// Number of blocks for the ramp-up period in the auction.
    pub ramp_up_period: u64,
    /// Maximum number of blocks a prover can lock a request before being slashed.
    pub lock_timeout: u64,
    /// Maximum number of blocks a request can stay unfulfilled before expiring.
    pub timeout: u64,
    /// Delay in seconds before bidding starts (added to current time).
    pub bidding_start_delay: u64,
}

impl Default for BoundlessParams {
    fn default() -> Self {
        Self {
            max_price_per_cycle: parse_units("0.001", "gwei").unwrap().try_into().unwrap(),
            min_price_per_cycle: parse_units("0.000", "gwei").unwrap().try_into().unwrap(),
            ramp_up_period: 10,
            lock_timeout: 600,
            timeout: 1200,
            bidding_start_delay: 5,
        }
    }
}
