[package]
name = "malda_rs"
version = "0.1.0"
edition = "2021"

[features]
default = []
guest = ["dep:methods"]

[dependencies]
alloy = { workspace = true }
alloy-primitives = { workspace = true }
anyhow = { workspace = true }
risc0-steel = { workspace = true, features = ["host"] }
risc0-op-steel = { workspace = true , features = ["host"]}
risc0-zkvm = { workspace = true, features = ["client", "unstable", "bonsai"] }
tracing-subscriber = { workspace = true }
url = { workspace = true }
alloy-consensus = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
bytemuck = { workspace = true }
methods = { workspace = true, optional = true }

reqwest = { version = "0.12.4", features = ["json"] }
bonsai-sdk =  "1.2.4"
bincode = "1.3.3"
tracing = "0.1.39"
dotenvy = "0.15"
boundless-market = "1.1.0"

malda_utils = { workspace = true }

# Linea block validation.
linea-block-verifier = { workspace = true, features = ["host"] }
