name: check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: System Info
        run: |
          uname -a
          nix --version

      - name: formatting
        run: nix build -L --no-link --show-trace .#checks.x86_64-linux.formatting

      - name: audit
        run: nix build -L --no-link --show-trace .#checks.x86_64-linux.audit

      # - name: clippy
      #   run: nix build -L --no-link --show-trace .#checks.x86_64-linux.clippy

      - name: guest
        run: nix build -L --no-link --show-trace .#packages.x86_64-linux.guest

      - name: methods
        run: nix build -L --no-link --show-trace .#packages.x86_64-linux.default

      - name: malda_rs
        run: nix build -L --no-link --show-trace .#packages.x86_64-linux.malda_rs
